# Generated by Django 4.1.2 on 2023-05-16 12:37

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='usuarios', variations={'thumb': {'height': 100, 'width': 100}}, verbose_name='Imagem'),
        ),
    ]
