# Generated by Django 3.1.7 on 2021-03-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20210317_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='aprovado',
            field=models.IntegerField(default=0, verbose_name='Aprovações'),
        ),
        migrations.AddField(
            model_name='camera',
            name='reprovado',
            field=models.IntegerField(default=0, verbose_name='Reprovações'),
        ),
    ]
