# Generated by Django 3.1 on 2021-03-18 10:12

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20210317_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('data', models.DateTimeField(verbose_name='Hora')),
                ('img', stdimage.models.StdImageField(upload_to='cameras', verbose_name='Imagem')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.camera')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
    ]
