# Generated by Django 3.1.7 on 2021-03-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='img',
            field=models.CharField(default='', max_length=200, verbose_name='Ultima Imagem'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='img',
            field=models.CharField(max_length=200, verbose_name='Ultima Imagem'),
        ),
    ]
