# Generated by Django 3.2.5 on 2021-09-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_auto_20210722_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='lastValue',
            field=models.IntegerField(default=0, verbose_name='última contagem'),
        ),
    ]
