# Generated by Django 3.2.3 on 2022-01-29 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('porta_img', models.IntegerField(default=32200, verbose_name='Porta de Imagem')),
                ('porta_dados', models.IntegerField(default=32100, verbose_name='Porta de Dados')),
                ('ip', models.CharField(max_length=15, unique=True, verbose_name='ip')),
                ('status', models.CharField(max_length=15, verbose_name='status')),
                ('aprovado', models.IntegerField(default=0, verbose_name='Aprovações')),
                ('reprovado', models.IntegerField(default=0, verbose_name='Reprovações')),
                ('garrafas', models.IntegerField(default=0, verbose_name='Total de Garrafas')),
                ('faltantes', models.IntegerField(default=0, verbose_name='Garrafas Faltantes')),
                ('img', models.CharField(default='', max_length=200, verbose_name='Ultima Imagem')),
                ('tipo', models.CharField(default='ve', max_length=15, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Câmera',
                'verbose_name_plural': 'Câmeras',
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('data', models.DateTimeField(verbose_name='Hora')),
                ('img', models.CharField(max_length=200, verbose_name='Ultima Imagem')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.camera')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
    ]
