# Generated by Django 3.1.7 on 2021-03-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20210317_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='porta',
        ),
        migrations.AddField(
            model_name='camera',
            name='porta_dados',
            field=models.IntegerField(default=32100, verbose_name='Porta de Dados'),
        ),
        migrations.AddField(
            model_name='camera',
            name='porta_img',
            field=models.IntegerField(default=32200, verbose_name='Porta de Imagem'),
        ),
    ]
