# Generated by Django 3.2.4 on 2021-07-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20210318_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='faltantes',
            field=models.IntegerField(default=0, verbose_name='Garrafas Faltantes'),
        ),
        migrations.AddField(
            model_name='camera',
            name='garrafas',
            field=models.IntegerField(default=0, verbose_name='Total de Garrafas'),
        ),
    ]
